### ISSUE TITLE
Handle system scope dependencies

### ISSUE THREAD

**Issue by sshikov** [zulily/dropship#2]
Its very hard and inconvenient to use dropship if you have system scoped dependencies like this:

```
        <dependency>
            <groupId>com.omd.jomd</groupId>
            <artifactId>jomd</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${env.ONE_TICK_HOME}/bin/jomd.jar</systemPath>
        </dependency>
```

dropship doesn't process expressions like maven does, so systemPath should be hardcoded.

**Comment by smreed** [comment]
Thanks for the issue. Are you able to work around this by setting `dropship.additional-paths` via the command line?

    -Ddropship.additional-paths=${ONE_TICK_HOME}/bin/jomd.jar

**Comment by smreed** [comment]
The fix ended up being quite simple, I think, I am throwing the system properties into the maven repository system session. This allows it to resolve variables, and I verified this with a local test project that included the JDK tools.jar as a system dependency.

You'll have to pull down the latest code and build dropship.jar yourself for the moment. Hopefully we'll release 1.2 to maven central soon.

**Comment by sshikov** [comment]
Am I right that this fix using properties only for resolution? I.e., I can't use ${env.}, but can set property value for ONE_TICK_HOME in my example above?

**Comment by smreed** [comment]
Ahh, you're right. I missed that when testing this out, only bothered to check system properties. You can work around it as you pointed out, wait for a fix (will be a few days at least before I can get to it), or submit a PR if you wish.

**Comment by smreed** [comment]
@sshikov would you mind testing the latest commit? it worked for my tests.

**Comment by sshikov** [comment]
Sure. We just have public holidays here. As soon as possible.

**Comment by sshikov** [comment]
BTW, some tests failed if runned from within intranet whene maven central is not available, because where is no joda-time version available.

Its not obvious how to setup mirror Nexus repository, used by projects and set in settings.xml.

**Comment by sshikov** [comment]
Properties works fine, thanks.
